Repository PLACE-4th-UMC/PLACE-server, pull requests merged in 2023-07, with the labels that each got.

#2 [feature/1-infra] 프로젝트 초기 설정
  place/.gitignore
  place/src/main/java/com/umc/place/comment/controller/CommentController.java
  place/src/main/java/com/umc/place/comment/entity/Comment.java
  place/src/main/java/com/umc/place/comment/repository/CommentRepository.java
  place/src/main/java/com/umc/place/comment/service/CommentService.java
  place/src/main/java/com/umc/place/common/BaseEntity.java
  place/src/main/java/com/umc/place/common/BaseException.java
  place/src/main/java/com/umc/place/common/BaseResponse.java
  place/src/main/java/com/umc/place/common/BaseResponseStatus.java
  place/src/main/java/com/umc/place/exhibition/controller/ExhibitionController.java
  place/src/main/java/com/umc/place/exhibition/entity/Exhibition.java
  place/src/main/java/com/umc/place/exhibition/repository/ExhibitionRepository.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
  place/src/main/java/com/umc/place/exhibitionLike/controller/ExhibitionLikeController.java
  place/src/main/java/com/umc/place/exhibitionLike/entity/ExhibitionLike.java
  place/src/main/java/com/umc/place/exhibitionLike/repository/ExhibitionLikeRepository.java
  place/src/main/java/com/umc/place/exhibitionLike/service/ExhibitionLikeService.java
  place/src/main/java/com/umc/place/story/controller/StoryController.java
  place/src/main/java/com/umc/place/story/entity/Story.java
  place/src/main/java/com/umc/place/story/repository/StoryRepository.java
  place/src/main/java/com/umc/place/story/service/StoryService.java
  place/src/main/java/com/umc/place/storyLike/controller/StoryLikeController.java
  place/src/main/java/com/umc/place/storyLike/entity/StoryLike.java
  place/src/main/java/com/umc/place/storyLike/repository/StoryLikeRepository.java
  place/src/main/java/com/umc/place/storyLike/service/StoryLikeService.java
  place/src/main/java/com/umc/place/user/controller/UserController.java
  place/src/main/java/com/umc/place/user/entity/Provider.java
  place/src/main/java/com/umc/place/user/entity/User.java
  place/src/main/java/com/umc/place/user/repository/UserRepository.java
  place/src/main/java/com/umc/place/user/service/UserService.java
Labels: 🛠️ infra

#4 [feature/1-infra] feat: Entity 생성
  place/.gitignore
  place/src/main/java/com/umc/place/comment/entity/Comment.java
  place/src/main/java/com/umc/place/exhibition/entity/Category.java
  place/src/main/java/com/umc/place/exhibition/entity/Exhibition.java
  place/src/main/java/com/umc/place/exhibitionLike/entity/ExhibitionLike.java
  place/src/main/java/com/umc/place/story/entity/Story.java
  place/src/main/java/com/umc/place/storyLike/entity/StoryLike.java
  place/src/main/java/com/umc/place/user/entity/Provider.java
  place/src/main/java/com/umc/place/user/entity/User.java
  place/src/main/resources/application.properties
Labels: 🛠️ infra

#6 [feature/5-getExhibitionDetail] 전시회 상세 조회 API
  place/src/main/java/com/umc/place/common/BaseResponseStatus.java
  place/src/main/java/com/umc/place/exhibition/controller/ExhibitionController.java
  place/src/main/java/com/umc/place/exhibition/dto/GetExhibitionDetailRes.java
  place/src/main/java/com/umc/place/exhibition/entity/Category.java
  place/src/main/java/com/umc/place/exhibition/entity/Exhibition.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
  place/src/main/java/com/umc/place/exhibitionLike/entity/ExhibitionLike.java
  place/src/main/java/com/umc/place/story/repository/StoryRepository.java
  place/src/main/java/com/umc/place/storyLike/entity/StoryLike.java
  place/src/main/java/com/umc/place/storyLike/repository/StoryLikeRepository.java
Labels: ✨ feature

#8 [feature/7-getStoryDetails] 스토리 상세 조회 api
  place/build.gradle
  place/src/main/java/com/umc/place/comment/dto/CommentResDto.java
  place/src/main/java/com/umc/place/comment/entity/Comment.java
  place/src/main/java/com/umc/place/common/BaseResponseStatus.java
  place/src/main/java/com/umc/place/exhibitionLike/entity/ExhibitionLike.java
  place/src/main/java/com/umc/place/story/controller/StoryController.java
  place/src/main/java/com/umc/place/story/dto/StoryDetailResponseDto.java
  place/src/main/java/com/umc/place/story/entity/Story.java
  place/src/main/java/com/umc/place/story/service/StoryService.java
  place/src/main/java/com/umc/place/storyLike/entity/StoryLike.java
Labels: ✨ feature, 🍊 sprint #1

#9 [feature/1-infra-fix] Home, Magazine 패키지 추가
  place/src/main/java/com/umc/place/home/controller/HomeController.java
  place/src/main/java/com/umc/place/home/service/HomeService.java
  place/src/main/java/com/umc/place/magazine/controller/MagazineController.java
  place/src/main/java/com/umc/place/magazine/service/MagazineService.java
Labels: 🛠️ infra

#10 [feature/5-likeExhibition] 전시회 좋아요 누르기 API
  place/src/main/java/com/umc/place/common/Constant.java
  place/src/main/java/com/umc/place/exhibition/controller/ExhibitionController.java
  place/src/main/java/com/umc/place/exhibition/dto/GetExhibitionDetailRes.java
  place/src/main/java/com/umc/place/exhibition/entity/ExhibitionLike.java
  place/src/main/java/com/umc/place/exhibition/repository/ExhibitionLikeRepository.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
  place/src/main/java/com/umc/place/exhibitionLike/controller/ExhibitionLikeController.java
  place/src/main/java/com/umc/place/exhibitionLike/repository/ExhibitionLikeRepository.java
  place/src/main/java/com/umc/place/exhibitionLike/service/ExhibitionLikeService.java
Labels: ✨ feature, 🍊 sprint #1

#15 [feature/7-getStoryDetails] Fix StoryDetailResDto
  place/src/main/java/com/umc/place/comment/dto/CommentResDto.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
  place/src/main/java/com/umc/place/story/controller/StoryController.java
  place/src/main/java/com/umc/place/story/dto/StoryDetailResponseDto.java
  place/src/main/java/com/umc/place/story/entity/Story.java
  place/src/main/java/com/umc/place/story/entity/StoryLike.java
  place/src/main/java/com/umc/place/story/repository/StoryLikeRepository.java
  place/src/main/java/com/umc/place/story/service/StoryService.java
  place/src/main/java/com/umc/place/storyLike/controller/StoryLikeController.java
  place/src/main/java/com/umc/place/storyLike/service/StoryLikeService.java
Labels: ✨ feature, 🍊 sprint #1
