Repository PLACE-4th-UMC/PLACE-server, pull requests merged in 2023-08, with the labels that each got.

#17 [feature/14-getMagazine] magazine API
  place/src/main/java/com/umc/place/exhibition/repository/ExhibitionLikeRepository.java
  place/src/main/java/com/umc/place/magazine/controller/MagazineController.java
  place/src/main/java/com/umc/place/magazine/dto/GetMagazineDetailRes.java
  place/src/main/java/com/umc/place/magazine/service/MagazineService.java
  place/src/main/java/com/umc/place/story/repository/StoryLikeRepository.java
Labels: ✨ feature, 🍊 sprint #1

#19 [feature/5-getExhibitions] 전시회 목록 조회 API
  place/src/main/java/com/umc/place/common/BaseResponseStatus.java
  place/src/main/java/com/umc/place/exhibition/controller/ExhibitionController.java
  place/src/main/java/com/umc/place/exhibition/dto/GetExhibitionsRes.java
  place/src/main/java/com/umc/place/exhibition/entity/Category.java
  place/src/main/java/com/umc/place/exhibition/entity/Exhibition.java
  place/src/main/java/com/umc/place/exhibition/repository/ExhibitionRepository.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
Labels: ✨ feature, 🍊 sprint #1

#20 [feature/5-searchExhibitions] 지역 기반 전시회 검색 구현
  place/src/main/java/com/umc/place/exhibition/controller/ExhibitionController.java
  place/src/main/java/com/umc/place/exhibition/repository/ExhibitionRepository.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
Labels: ✨ feature, 🍊 sprint #1

#21 [feature/7-storyUploadView] 스토리 업로드 페이지 뷰 조회
  place/src/main/java/com/umc/place/common/BaseResponse.java
  place/src/main/java/com/umc/place/common/BaseResponseStatus.java
  place/src/main/java/com/umc/place/story/controller/StoryController.java
  place/src/main/java/com/umc/place/story/repository/StoryRepository.java
  place/src/main/java/com/umc/place/story/service/StoryService.java
Labels: ✨ feature, 🍊 sprint #1

#22 [feat/7-uploadStoryComment] 스토리 댓글 작성
  place/src/main/java/com/umc/place/comment/dto/CommentUploadReqDto.java
  place/src/main/java/com/umc/place/comment/dto/CommentUploadResDto.java
  place/src/main/java/com/umc/place/comment/entity/Comment.java
  place/src/main/java/com/umc/place/comment/service/CommentService.java
  place/src/main/java/com/umc/place/story/controller/StoryController.java
  place/src/main/java/com/umc/place/story/dto/StoryDetailResponseDto.java
  place/src/main/java/com/umc/place/story/service/StoryService.java
Labels: ✨ feature, 🍊 sprint #1

#23 #18 feat: S3 API 구현
  place/build.gradle
  place/src/main/java/com/umc/place/common/config/AWSConfig.java
  place/src/main/java/com/umc/place/common/controller/FileUploadController.java
  place/src/main/java/com/umc/place/common/service/S3Upload.java
Labels: 🍊 sprint #1

#24 Feature/13 user social login
  place/src/main/java/com/umc/place/common/BaseResponseStatus.java
  place/src/main/java/com/umc/place/common/Constant.java
  place/src/main/java/com/umc/place/user/OAuth2/dto/KakaoTokenResponse.java
  place/src/main/java/com/umc/place/user/OAuth2/service/KakaoAuthService.java
  place/src/main/java/com/umc/place/user/controller/UserController.java
  place/src/main/java/com/umc/place/user/dto/LoginRequest.java
  place/src/main/java/com/umc/place/user/dto/PatchProfileReq.java
  place/src/main/java/com/umc/place/user/dto/PostNewUserReq.java
  place/src/main/java/com/umc/place/user/dto/PostNicknameReq.java
  place/src/main/java/com/umc/place/user/dto/PostUserRes.java
  place/src/main/java/com/umc/place/user/entity/Provider.java
  place/src/main/java/com/umc/place/user/entity/User.java
  place/src/main/java/com/umc/place/user/repository/UserRepository.java
  place/src/main/java/com/umc/place/user/service/AuthService.java
  place/src/main/java/com/umc/place/user/service/UserService.java
Labels: ✨ feature, 🍊 sprint #1

#28 [fix/13-userSocialLogin] 로그아웃, 회원 탈퇴
  place/src/main/java/com/umc/place/user/OAuth2/dto/GoogleTokenResponse.java
  place/src/main/java/com/umc/place/user/OAuth2/dto/NaverTokenResponse.java
  place/src/main/java/com/umc/place/user/OAuth2/service/GoogleAuthService.java
  place/src/main/java/com/umc/place/user/OAuth2/service/KakaoAuthService.java
  place/src/main/java/com/umc/place/user/OAuth2/service/NaverAuthService.java
  place/src/main/java/com/umc/place/user/controller/UserController.java
  place/src/main/java/com/umc/place/user/dto/LoginRequest.java
  place/src/main/java/com/umc/place/user/dto/PostTokenReq.java
  place/src/main/java/com/umc/place/user/entity/User.java
  place/src/main/java/com/umc/place/user/repository/UserRepository.java
  place/src/main/java/com/umc/place/user/service/UserService.java
Labels: 🔨 fix, 🍊 sprint #1

#29 [fix/13-userPage] user 페이지 스토리 목록 추가
  place/build.gradle
  place/src/main/java/com/umc/place/story/repository/StoryRepository.java
  place/src/main/java/com/umc/place/user/controller/UserController.java
  place/src/main/java/com/umc/place/user/dto/GetProfileRes.java
  place/src/main/java/com/umc/place/user/dto/LoginRequest.java
  place/src/main/java/com/umc/place/user/entity/User.java
  place/src/main/java/com/umc/place/user/repository/UserRepository.java
  place/src/main/java/com/umc/place/user/service/AuthService.java
  place/src/main/java/com/umc/place/user/service/UserService.java
Labels: 🔨 fix, 🍊 sprint #1

#31 [feature/11-getHome] 홈 API
  place/src/main/java/com/umc/place/exhibition/repository/ExhibitionRepository.java
  place/src/main/java/com/umc/place/home/controller/HomeController.java
  place/src/main/java/com/umc/place/home/dto/GetHomeUserLikeDetailRes.java
  place/src/main/java/com/umc/place/home/dto/GetHomeUserRecentDetailRes.java
  place/src/main/java/com/umc/place/home/dto/GetHomeUserViewDetailRes.java
  place/src/main/java/com/umc/place/home/service/HomeService.java
  place/src/main/java/com/umc/place/magazine/dto/GetMagazineDetailRes.java
Labels: 🍊 sprint #1

#33 [feature/5-getExhibitionDetail-fix] user 조회 수정
  place/src/main/java/com/umc/place/exhibition/controller/ExhibitionController.java
  place/src/main/java/com/umc/place/exhibition/service/ExhibitionService.java
  place/src/main/java/com/umc/place/user/repository/UserRepository.java
Labels: 🔨 fix, 🍊 sprint #1

#35 Feature/18 s3
  place/src/main/java/com/umc/place/common/controller/FileUploadController.java
  place/src/main/java/com/umc/place/common/entity/S3.java
  place/src/main/java/com/umc/place/common/repository/S3Repository.java
  place/src/main/java/com/umc/place/common/service/S3Upload.java
  place/src/main/java/com/umc/place/story/entity/Story.java
  place/src/main/java/com/umc/place/user/entity/User.java
Labels: ✨ feature, 🍊 sprint #1

#36 [fix/13-userSocialLogin] 소셜 로그인 수정
  place/build.gradle
  place/src/main/java/com/umc/place/common/config/RedisConfig.java
  place/src/main/java/com/umc/place/user/OAuth2/dto/NaverTokenResponse.java
  place/src/main/java/com/umc/place/user/OAuth2/service/GoogleAuthService.java
  place/src/main/java/com/umc/place/user/OAuth2/service/KakaoAuthService.java
  place/src/main/java/com/umc/place/user/OAuth2/service/NaverAuthService.java
  place/src/main/java/com/umc/place/user/entity/User.java
  place/src/main/java/com/umc/place/user/repository/UserRepository.java
  place/src/main/java/com/umc/place/user/service/UserService.java
Labels: 🔨 fix, 🍊 sprint #1

#45 [fix/44-cors] CORS 이슈 해결
  .github/workflows/main.yml
  place/appspec.yml
  place/build.gradle
  place/scripts/start.sh
  place/scripts/stop.sh
  place/src/main/java/com/umc/place/common/TestController.java
  place/src/main/java/com/umc/place/common/config/WebConfig.java
  place/src/main/resources/test.java
Labels: 🔨 fix
